server:
  port: 8081

spring:
  datasource:
    druid:
      url: jdbc:mysql:///school_map_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

  profiles:
    include: com