server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://222.200.20.8:3306/crm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

  profiles:
    include: com